name: Update Contributions in README.md every day

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: 0 1 * * *

jobs:

  update-contributions:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check awk exist
        run: apt-cache policy awk

      - name: Make script executable
        run: chmod +x updateContributions.sh

      - name: Execute python script
        run: ./updateContributions.sh
        # run: entireContributions=`python3 contributionDetails.py`
        env:
          GRAPHQL_ENDPOINT: ${{ vars.GRAPHQL_ENDPOINT }}
          PROFILE_READ_TOKEN: ${{ secrets.PROFILE_READ_TOKEN }}
          

      # - name: Modify README to add latest total contribution
      #   run: awk -v var="$entireContributions" '{sub(/- Total Contributions in GitHub: [0-9]+/, "- Total Contributions in GitHub: **" var "**");} {print}' README.md > TEMP_README.md && mv TEMP_README.md README.md

      - name: Commit the changes to git
        run: |
          git add .
          git diff
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git commit -m "Updated README" -a || echo "No changes to commit"

      - name: Push to GitHub
        run: git push
