name: Update Contributions in README.md every day

on:
  schedule:
    - cron: 0 1 * * *

jobs:

  update-contributions:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update and upgrade
        run: sudo apt-get update -y && sudo apt-get upgrade -y

      - name: Install awk
        run: sudo apt-get install gawk

      - name: Make script executable
        run: chmod +x updateContributions.sh

      - name: Execute script for updating contributions
        run: ./updateContributions.sh
        env:
          GRAPHQL_ENDPOINT: ${{ vars.GRAPHQL_ENDPOINT }}
          PROFILE_READ_TOKEN: ${{ secrets.PROFILE_READ_TOKEN }}

      - name: Commit the changes to git
        run: |
          git add .
          git diff
          git config --global user.email "ashishsamtgeorge@gmail.com"
          git config --global user.name "pepashish"
          git commit -m "Updated README" -a || echo "No changes to commit"

      - name: Push to GitHub
        run: git push
